"""add clause_type to policy_chunks"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = '06b3f50e1d3d'
down_revision: Union[str, Sequence[str], None] = 'bfadc12f6bdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Existing rows have no clause_type value and the corpus is always fully
    # rebuilt by `python -m app.scripts.ingest_policies` anyway (it clears
    # and reinserts every row), so clear the table here rather than trying
    # to backfill a value — re-run ingestion right after this migration.
    op.execute("DELETE FROM policy_chunks")
    op.add_column('policy_chunks', sa.Column('clause_type', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('policy_chunks', 'clause_type')
    # ### end Alembic commands ###
