"""add is_core_procedure to policy_chunks"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = '6ba7f2b80426'
down_revision: Union[str, Sequence[str], None] = '06b3f50e1d3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('policy_chunks', sa.Column('is_core_procedure', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('policy_chunks', 'is_core_procedure')
    # ### end Alembic commands ###
