"""add decision_action to complaint_timeline_events"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = '714edda34240'
down_revision: Union[str, Sequence[str], None] = '6ba7f2b80426'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaint_timeline_events', sa.Column('decision_action', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('complaint_timeline_events', 'decision_action')
    # ### end Alembic commands ###
