"""add policy chunks table"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = 'bfadc12f6bdb'
down_revision: Union[str, Sequence[str], None] = '7d0d9e401091'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policy_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('clause', sa.String(length=255), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding', sa.ARRAY(sa.Float()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_policy_chunks'))
    )
    op.create_index(op.f('ix_policy_chunks_category'), 'policy_chunks', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_policy_chunks_category'), table_name='policy_chunks')
    op.drop_table('policy_chunks')
    # ### end Alembic commands ###
